### ISSUE TITLE
Assignment 3 - Dear Data Visualization

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/quant-humanists-2018#10]
** Please post your links below. Thanks!** 👇

**Comment by mengzhenxiao** [comment]
https://www.mengzhenxiao.com/single-post/2018/02/11/Assignment-03-Dear-Data-Visualization

**Comment by xiranisabear** [comment]
https://xiranisabearblog.wordpress.com/2018/02/11/week-3-self-track-outfit-tracking/

**Comment by mikibinxue** [comment]
https://gist.github.com/mikibinxue/b5c3ba0785b613e359fdb1ee3858b111

**Comment by kriziaf** [comment]
https://kernfern.wordpress.com/2018/02/12/analog-tracking-my-daily-commute/

**Comment by chloemar10** [comment]
https://gist.github.com/chloemar10/bdbaaab80206b8441fcdcd8aca2c7f90

**Comment by alicehgsun** [comment]
http://www.alicehgsun.xyz/quant-humanists/dear-data-visualization/

**Comment by ghost** [comment]
https://gist.github.com/hnedunuri/947b70798747e6db20eca70b5bfa0432
