### ISSUE TITLE
Assignment 4 - Mini Service Design Concept

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/quant-humanists-2018#11]
**please place your links below. thank you!**
(not due until Feb 26)

**Comment by kriziaf** [comment]
https://kernfern.wordpress.com/2018/02/26/on-data-transparency-in-the-surveillance-economy/

**Comment by chloemar10** [comment]
https://gist.github.com/chloemar10/895f0a6b0b97c2d69b1da67e9259ee58

**Comment by mengzhenxiao** [comment]
https://www.mengzhenxiao.com/single-post/2018/02/25/Assignment-04-Quant-Self-as-a-Service

**Comment by xiranisabear** [comment]
https://xiranisabearblog.wordpress.com/2018/02/26/week-4-service-design/

**Comment by mikibinxue** [comment]
https://gist.github.com/mikibinxue/0ba046438aed81fc11c0baa4daf28134

**Comment by xujenna** [comment]
http://www.xujenna.com/itp_blog/2018/02/26/846/

**Comment by alicehgsun** [comment]
http://www.alicehgsun.xyz/quant-humanists/quant-self-service/

**Comment by dashkinok** [comment]
https://gist.github.com/dashkinok/6ee1e1ae58db0c247c72496c7fd7686c

**Comment by ghost** [comment]
https://gist.github.com/hnedunuri/fd34e53293678002a67f55e61246c707
