### ISSUE TITLE
Assignment 5 - Quant Self Intervention

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/quant-humanists-2018#13]
**Please drop your links in the comments below. Thanks!**

**Comment by chloemar10** [comment]
https://gist.github.com/chloemar10/771f92aadf168e483a2f1098ec7489e4

**Comment by xujenna** [comment]
http://www.xujenna.com/itp_blog/2018/03/05/qh-w5-hw-quant-self-intervention/

**Comment by alicehgsun** [comment]
http://www.alicehgsun.xyz/quant-humanists/quant-self-intervention/

**Comment by mikibinxue** [comment]
https://gist.github.com/mikibinxue/e83775c2e7b0e8432efca8fc63d2591c

**Comment by ghost** [comment]
https://gist.github.com/hnedunuri/a7747ce3bbd541b802bb3c9e6d099bd4

**Comment by dollarbilll** [comment]
https://docs.google.com/presentation/d/1hOFhnqWHMQITA6_oyjcyzwQbw5DE_1ru4975fyraD8E/edit?usp=sharing

**Comment by mengzhenxiao** [comment]
https://www.mengzhenxiao.com/single-post/2018/03/03/Assignment-05-Design-a-quantified-self-intervention

**Comment by dashkinok** [comment]
https://gist.github.com/dashkinok/b2d7743c03a70ab78083741583325e27

**Comment by xiranisabear** [comment]
https://xiranisabearblog.wordpress.com/2018/03/05/week-6-quant-self-intervention/

**Comment by kriziaf** [comment]
https://kernfern.wordpress.com/2018/03/13/self-talk-intervention-using-alexa
