### ISSUE TITLE
Assignment 6 - Hack your tracker

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/quant-humanists-2018#15]
** hope you're all having a great spring break! please put your assignments links below per usual. Thanks!**

**Comment by ghost** [comment]
https://gist.github.com/hnedunuri/93c5f84afc2b013a784419433d26ff68

**Comment by mengzhenxiao** [comment]
https://www.mengzhenxiao.com/single-post/2018/03/18/Assignment-06-Hack-your-tracker-Untrack-me

**Comment by alicehgsun** [comment]
http://www.alicehgsun.xyz/quant-humanists/untrack-me/

**Comment by xiranisabear** [comment]
https://xiranisabearblog.wordpress.com/2018/03/19/week-6-un-track-me/

**Comment by mikibinxue** [comment]
https://gist.github.com/mikibinxue/6851d24fe94e0e5ba7553a6a25a8a38f

**Comment by xujenna** [comment]
http://www.xujenna.com/itp_blog/2018/03/19/qh-wk-06-untrack-me/

**Comment by chloemar10** [comment]
https://gist.github.com/chloemar10/c2094aed2ccacd4d25d973fc5e28e3f6

**Comment by kriziaf** [comment]
https://kernfern.wordpress.com/2018/03/19/data-obfuscation-with-tamper-monkey/

**Comment by joeyklee** [comment]
https://williamfhallett.wordpress.com/portfolio/quant-humanists-the-i-in-api/
