### ISSUE TITLE
Assignment 1 - Blog Post: Quant Self Project Review

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/quant-humanists-2018#3]
**Please drop your links into the comments below. Thank you!**

**Comment by kriziaf** [comment]
https://kernfern.wordpress.com/2018/01/28/three-self-tracking-projects/

**Comment by chloemar10** [comment]
https://gist.github.com/chloemar10/6b1006f1489e3e10d1564f98d7dab7ee

**Comment by ghost** [comment]
https://gist.github.com/hnedunuri/4defb1a9d408771d43b57d2b08924546

**Comment by mikibinxue** [comment]
https://gist.github.com/mikibinxue/40ce835486ff3db799e5ab5bc94e8cf7

**Comment by dashkinok** [comment]
https://gist.github.com/dashkinok/33a29957c07984935dce3be95148a471

**Comment by xiranisabear** [comment]
https://xiranisabearblog.wordpress.com/2018/01/28/assignment1-self-tracking-project-review/

**Comment by alicehgsun** [comment]
http://www.alicehgsun.xyz/quant-humanists/quant-self-project/

**Comment by avigailvantu** [comment]
https://gist.github.com/avigailvantu/fdb64bd4ec6215cf3159de8d3ab0811d

**Comment by mengzhenxiao** [comment]
https://gist.github.com/mengzhenxiao/1b69b0ccda3ee8c3d2efb37e703c4d55

**Comment by xujenna** [comment]
http://www.xujenna.com/itp_blog/2018/01/29/quant-humanists-w1-hw-quant-self-project-review/

**Comment by tianrandesign** [comment]
https://gist.github.com/tianrandesign/0387b9a8a14126480b13e6945a513836

**Comment by kaichehung** [comment]
https://gist.github.com/kaichehung/03611dd023ad177fd2604bbeb11d3357
