### ISSUE TITLE
Week_02: Mini-brief // Data Modeling Exercise

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/quant-humanists-2018#5]
... for our little in-class exercise...

**Comment by kaichehung** [comment]
https://gist.github.com/kaichehung/19b0e78c0fd27433f570387056a723af

**Comment by xujenna** [comment]
https://gist.github.com/xujenna/7df4484377ed497d27f8db09a5fb49a5

**Comment by kriziaf** [comment]
https://gist.github.com/kriziaf/3645491b263ce9e914c1411973915b63

**Comment by mengzhenxiao** [comment]
https://gist.github.com/mengzhenxiao/fb02fe90980f12eb621052c4ddcfa594

**Comment by alicehgsun** [comment]
https://gist.github.com/alicehgsun/34ec96ad2d3c295048d0f14f63444b12

**Comment by xiranisabear** [comment]
https://gist.github.com/xiranisabear/91e986ad2e204fb9d2b69f03d874ef55

**Comment by chloemar10** [comment]
https://gist.github.com/chloemar10/8cb17221fc20220a2a714ed24c1dc88f

**Comment by tianrandesign** [comment]
https://gist.github.com/tianrandesign/600cd942981711a2696f4306e2454fa0

**Comment by dashkinok** [comment]
https://gist.github.com/dashkinok/fd71977ab8132903310d78040bc46363

**Comment by mikibinxue** [comment]
https://gist.github.com/mikibinxue/6a1f7eca1b0712f10ba976d31b0b580a

**Comment by dollarbilll** [comment]
https://gist.github.com/dollarbilll/2ebfab9216e1bdd137a8e7d61a154394

**Comment by ghost** [comment]
https://gist.github.com/hnedunuri/d1d1dcd0a65314f6a67b60600bbc9100

**Comment by avigailvantu** [comment]
https://gist.github.com/avigailvantu/0722a6a7bd666c7261cdc2587dbbc153
