### ISSUE TITLE
Assignment 2 - Document Your Methodology OR DIY Tracking Methodology

### ISSUE THREAD

**Issue by joeyklee** [joeyklee/quant-humanists-2018#7]
**Please drop your links below. Thanks!**

**Comment by mengzhenxiao** [comment]
https://www.mengzhenxiao.com/single-post/2018/02/04/Assignment-02-Track-My-Self-track-Methodology

**Comment by alicehgsun** [comment]
http://www.alicehgsun.xyz/quant-humanists/document-your-methodology/

**Comment by xiranisabear** [comment]
https://xiranisabearblog.wordpress.com/2018/02/05/week-2-methodology-and-reflection/

**Comment by kriziaf** [comment]
https://kernfern.wordpress.com/2018/02/02/%F0%9F%8D%B5-matchadata-a-public-quantified-self-experiment/

**Comment by chloemar10** [comment]
https://gist.github.com/chloemar10/5f87fd49cd67210e8d9c19bf2333161f

**Comment by mikibinxue** [comment]
https://gist.github.com/mikibinxue/343b0ea7a13993efab47ad701d17d859

**Comment by xujenna** [comment]
http://www.xujenna.com/itp_blog/2018/02/05/qh-w2-hw-document-your-methodology/

**Comment by ghost** [comment]
https://gist.github.com/hnedunuri/984b8aa46d4ea137735dbbfe352de21b

**Comment by dashkinok** [comment]
https://gist.github.com/dashkinok/809eec783046666080b321d0919e657b

**Comment by dollarbilll** [comment]
https://williamfhallett.wordpress.com/portfolio/quant-humanists-the-i-in-api/
